### ISSUE TITLE
[MinGW64] ncurses crashes (memory leak?)

### ISSUE THREAD

**Issue by Fighter19** [Alexpux/MSYS2-packages#1081]
When trying to execute initscr() from the ncurses library (MinGW64)
It crashes the program.

```
#0  0x00007ffaa976771f in ntdll!RtlIsNonEmptyDirectoryReparsePointAllowed ()
   from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ffaa976df0a in ntdll!RtlpNtSetValueKey ()
   from C:\Windows\SYSTEM32\ntdll.dll
#2  0x00007ffaa9714f22 in wcstok_s () from C:\Windows\SYSTEM32\ntdll.dll
#3  0x00007ffaa9729048 in ntdll!memset () from C:\Windows\SYSTEM32\ntdll.dll
#4  0x00007ffaa8bc995c in msvcrt!free () from C:\Windows\System32\msvcrt.dll
#5  0x00000000004309ed in really_free_termtype ()
#6  0x000000000041060f in _nc_setupterm_ex ()
#7  0x00000000004071da in newterm_sp ()
#8  0x00000000004075ab in newterm ()
#9  0x00000000004058c3 in initscr ()
#10 0x0000000000401582 in main () at CURHELLO.C:26
```

ncurses-devel is at the current version (6.0.20170708-2)
the MinGW64 package is at the current version (6.0.20170916-1).

The program was compiled using
```
gcc -g -I/mingw64/include/ncursesw/ CURHELLO.C -lncurses
```
from here:
[http://www.paulgriffiths.net/program/c/srcs/curhellosrc.html](url)

This also occurs with DosBox 0.74 in Debug Mode.

**Comment by Fighter19** [comment]
It seems this problem only occurs when starting a program from the shell.
This does not happen when a program gets started separately.
