### ISSUE TITLE
python3: Mismatched version of setuptools bundled in ensurepip

### ISSUE THREAD

**Issue by koniiiik** [Alexpux/MSYS2-packages#1325]
`/usr/lib/python3.6/ensurepip/__init__.py:13` says:

    _SETUPTOOLS_VERSION = "39.2.0"

However, the actual wheel bundled in `/usr/lib/python3.6/ensurepip/_bundled/` is `setuptools-39.0.1-py2.py3-none-any.whl`. This means that ensure pip fails; among other things, this breaks venv.

How to reproduce:

```
me@computer ~ $  python -m venv msys-env
Error: Command '['/c/Users/me/msys-env/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
me@computer ~ $  ./msys-env/bin/python -Im ensurepip --upgrade --default-pip
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/usr/lib/python3.6/ensurepip/__init__.py", line 239, in _main
    default_pip=args.default_pip,
  File "/usr/lib/python3.6/ensurepip/__init__.py", line 136, in _bootstrap
    shutil.copy(whl, tmpdir)
  File "/usr/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.6/ensurepip/_bundled/setuptools-39.2.0-py2.py3-none-any.whl'
```

**Comment by koniiiik** [comment]
Hmm, so upon further inspection, it's not just that the version of setuptools is wrong, ensurepip is more broken than that – even if you fix the version of setuptools, it fails to find `six-1.10.0-py2.py3-none-any.whl`, which is simply not there.

**Comment by will** [comment]
I’ll try
