### ISSUE TITLE
Python 3.7.0 scipy curve_fit failed loading

### ISSUE THREAD

**Issue by xiaowen64** [Alexpux/MSYS2-packages#1373]
Python 3.7.0 (default, Aug  3 2018, 11:56:18)  [GCC 8.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
'>>>' from scipy.optimize import curve_fit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\optimize\__init__.py", line 271, in <module>
    from ._minimize import *
  File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\optimize\_minimize.py", line 21, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\sparse\linalg\__init__.py", line 117, in <module>
    from .eigen import *
  File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "C:/msys64/mingw64/lib/python3.7/site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: The specified module could not be found.

**Comment by Alexpux** [comment]
@xiaowen64 wrong place for issue. Mingw programs issues must be in MINGW-packages repo.
In any case new arpack 3.6.2 uploaded
