### ISSUE TITLE
Can't build ruby extension with msys/ruby 2.1.5-1

### ISSUE THREAD

**Issue by mario-grgic** [Alexpux/MSYS2-packages#364]
I am trying to build command-t vim plugin for msys/vim 7.4.872-2 which was built against msys/ruby 2.1.5-1 (also installed).

/usr/bin/vi :version prints

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 16 2015 08:44:57)
Included patches: 1-872
Compiled by <alexpux@gmail.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +cscope          +folding         +menu            +netbeans_intg   -sniff           +virtualedit
+arabic          +cursorbind      -footer          +mksession       +path_extra      +startuptime     +visual
+autocmd         +cursorshape     +fork()          +modify_fname    +perl/dyn        +statusline      +visualextra
-balloon_eval    +dialog_con      +gettext         +mouse           +persistent_undo -sun_workshop    +viminfo
-browse          +diff            -hangul_input    -mouseshape      +postscript      +syntax          +vreplace
++builtin_terms  +digraphs        +iconv           +mouse_dec       +printer         +tag_binary      +wildignore
+byte_offset     -dnd             +insert_expand   -mouse_gpm       +profile         +tag_old_static  +wildmenu
+cindent         -ebcdic          +jumplist        -mouse_jsbterm   +python/dyn      -tag_any_white   +windows
-clientserver    +emacs_tags      +keymap          +mouse_netterm   +python3/dyn     -tcl             +writebackup
+clipboard       +eval            +langmap         +mouse_sgr       +quickfix        +terminfo        -X11
+cmdline_compl   +ex_extra        +libcall         -mouse_sysmouse  +reltime         +termresponse    -xfontset
+cmdline_hist    +extra_search    +linebreak       +mouse_urxvt     +rightleft       +textobjects     -xim
+cmdline_info    +farsi           +lispindent      +mouse_xterm     +ruby/dyn        +title           -xsmp
+comments        +file_in_path    +listcmds        +multi_byte      +scrollbind      -toolbar         -xterm_clipboard
+conceal         +find_in_path    +localmap        +multi_lang      +signs           +user_commands   -xterm_save
+cryptv          +float           -lua             -mzscheme        +smartindent     +vertsplit       -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2 -I/usr/include/ncursesw  -march=x86-64 -mtune=gene
ric -O2 -pipe -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -pipe -fstack-protector -pipe -Wl,--as-needed -o vim.exe        -lm    -lncursesw -liconv -lintl   -p
ipe -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong  -L/usr/lib/
perl5/core_perl/CORE -lperl -lpthread -ldl -lcrypt
```

And simple commands like ```:ruby puts 1``` work just fine in Vim. 

However, if I download the command-t plugin which needs ruby native C extension and try to build it, I run into following problems:

First /usr/include is not on include path. This can be fixed by passing a flag to ```ruby extconf.rb --with-opt-dir=/usr```

But the next problem is complaining about missing win32.h and conflicting type definitions:

```
$ ruby extconf.rb --with-opt-dir=/usr/
checking for float.h... /usr/lib/ruby/2.1.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.1.0/mkmf.rb:588:in `try_cpp'
        from /usr/lib/ruby/2.1.0/mkmf.rb:1121:in `block in find_header'
        from /usr/lib/ruby/2.1.0/mkmf.rb:919:in `block in checking_for'
        from /usr/lib/ruby/2.1.0/mkmf.rb:352:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.1.0/mkmf.rb:322:in `open'
        from /usr/lib/ruby/2.1.0/mkmf.rb:352:in `block in postpone'
        from /usr/lib/ruby/2.1.0/mkmf.rb:322:in `open'
        from /usr/lib/ruby/2.1.0/mkmf.rb:348:in `postpone'
        from /usr/lib/ruby/2.1.0/mkmf.rb:918:in `checking_for'
        from /usr/lib/ruby/2.1.0/mkmf.rb:1120:in `find_header'
        from extconf.rb:7:in `header'
        from extconf.rb:14:in `<main>'
$
```

Here is the mkmf.log 

```
"gcc -o conftest.exe -I/usr/include/ruby-2.1.0/x86_64-msys -I/usr/include/ruby-2.1.0/ruby/backward -I/usr/include/ruby-2.1.0 -I. -I/usr//include -D_FORTIFY_SOURCE=2   -march=x86-64 -mtune=generic -O2 -pipe -fno-strict-aliasing  conftest.c  -L. -L/usr/lib -L/usr//lib -L. -pipe -fstack-protector     -lruby210  -lpthread -lgmp -ldl -lcrypt  "
In file included from C:/msys64/usr/include/stdio.h:48:0,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby/defines.h:26,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby/ruby.h:29,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby.h:33,
                 from conftest.c:1:
C:/msys64/usr/include/sys/types.h:124:18: error: conflicting types for 'time_t'
 typedef _TIME_T_ time_t;
                  ^
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/stddef.h:7:0,
                 from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/5.2.0/include/stddef.h:1,
                 from C:/msys64/usr/include/sys/cdefs.h:45,
                 from C:/msys64/usr/include/stdio.h:35,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby/defines.h:26,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby/ruby.h:29,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby.h:33,
                 from conftest.c:1:
C:/msys64/mingw64/x86_64-w64-mingw32/include/crtdefs.h:138:20: note: previous declaration of 'time_t' was here
 typedef __time64_t time_t;
                    ^
In file included from C:/msys64/usr/include/ruby-2.1.0/ruby/defines.h:51:0,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby/ruby.h:29,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby.h:33,
                 from conftest.c:1:
C:/msys64/usr/include/inttypes.h:23:0: warning: "__STRINGIFY" redefined
 #define __STRINGIFY(a) #a
 ^
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/_mingw.h:12:0,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/crtdefs.h:10,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/stddef.h:7,
                 from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/5.2.0/include/stddef.h:1,
                 from C:/msys64/usr/include/sys/cdefs.h:45,
                 from C:/msys64/usr/include/stdio.h:35,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby/defines.h:26,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby/ruby.h:29,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby.h:33,
                 from conftest.c:1:
C:/msys64/mingw64/x86_64-w64-mingw32/include/_mingw_mac.h:10:0: note: this is the location of the previous definition
 #define __STRINGIFY(x) #x
 ^
In file included from C:/msys64/usr/include/ruby-2.1.0/ruby/ruby.h:29:0,
                 from C:/msys64/usr/include/ruby-2.1.0/ruby.h:33,
                 from conftest.c:1:
C:/msys64/usr/include/ruby-2.1.0/ruby/defines.h:217:24: fatal error: ruby/win32.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by Alexpux** [comment]
You mix MINGW and MSYS gcc

**Comment by mario-grgic** [comment]
Yes, thank you. This was my problem.
