### ISSUE TITLE
openssl 1.0.2.g breaks pip3

### ISSUE THREAD

**Issue by goreliu** [Alexpux/MSYS2-packages#488]
```
$ pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==8.0.3', 'console_scripts', 'pip')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python3.4/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/lib/python3.4/site-packages/pip/index.py", line 29, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/lib/python3.4/site-packages/pip/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/usr/lib/python3.4/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/usr/lib/python3.4/site-packages/pip/_vendor/distlib/compat.py", line 66, in <module>
    from urllib.request import (urlopen, urlretrieve, Request, url2pathname,
ImportError: cannot import name 'HTTPSHandler'
```

openssl 1.0.2.f is OK.

Windows 10 64bit, 64bit msys2.

**Comment by zhuangmax** [comment]
I met with similar issue.  after downgrading from mingw-w64-x86_64-openssl-1.0.2.g-1-any.pkg.tar.xz to mingw-w64-x86_64-openssl-1.0.2.f-1-any.pkg.tar.xz,  pip works,   but pip3 still complains "ImportError: cannot import name 'HTTPSHandler'"

**Comment by binglinli** [comment]
I met with the some issue.
