### ISSUE TITLE
Ruby gem installations not working win32/resolv

### ISSUE THREAD

**Issue by pecigonzalo** [Alexpux/MSYS2-packages#515]
Article in Japanse describing the same issue:
http://qiita.com/from_kyushu/items/a13b501026f01829996b

Output:
```
gem install bundler
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file-- win32/resolv (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.3.0/resolv.rb:971:in `default_config_hash'
        from /usr/lib/ruby/2.3.0/resolv.rb:989:in `block in lazy_initialize'
        from /usr/lib/ruby/2.3.0/resolv.rb:982:in `synchronize'
        from /usr/lib/ruby/2.3.0/resolv.rb:982:in `lazy_initialize'
        from /usr/lib/ruby/2.3.0/resolv.rb:360:in `block in lazy_initialize'
        from /usr/lib/ruby/2.3.0/resolv.rb:358:in `synchronize'
        from /usr/lib/ruby/2.3.0/resolv.rb:358:in `lazy_initialize'
        from /usr/lib/ruby/2.3.0/resolv.rb:518:in `fetch_resource'
        from /usr/lib/ruby/2.3.0/resolv.rb:512:in `each_resource'
        from /usr/lib/ruby/2.3.0/resolv.rb:493:in `getresource'
        from /usr/lib/ruby/2.3.0/rubygems/remote_fetcher.rb:99:in `api_endpoint'
        from /usr/lib/ruby/2.3.0/rubygems/source.rb:47:in `api_uri'
        from /usr/lib/ruby/2.3.0/rubygems/source.rb:86:in `dependency_resolver_set'
        from /usr/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:24:in `block in pick_sets'
        from /usr/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each'
        from /usr/lib/ruby/2.3.0/rubygems/source_list.rb:98:in `each_source'
        from /usr/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:23:in `pick_sets'
        from /usr/lib/ruby/2.3.0/rubygems/resolver/best_set.rb:29:in `find_all'
        from /usr/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:152:in `find_all'
        from /usr/lib/ruby/2.3.0/rubygems/resolver/installer_set.rb:55:in `add_always_install'
        from /usr/lib/ruby/2.3.0/rubygems/dependency_installer.rb:474:in `resolve_dependencies'

        from /usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:239:in `install_gem'
        from /usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in `block in install_gems'
        from /usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `each'
        from /usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `install_gems'
        from /usr/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in `execute'
        from /usr/lib/ruby/2.3.0/rubygems/command.rb:308:in `invoke_with_build_args'
        from /usr/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
        from /usr/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
        from /usr/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
        from /usr/bin/gem:21:in `<main>'
```

**Comment by pecigonzalo** [comment]
https://bugs.ruby-lang.org/issues/12071

That seem to be the cause.

**Comment by Alexpux** [comment]
Create pull request with patch

**Comment by pecigonzalo** [comment]
Yeah i was trying to do that, im not well versed on submitting patchs for this.
