### ISSUE TITLE
msys Python's ctypes broken by msys2-runtime > 2.5.0

### ISSUE THREAD

**Issue by bgamari** [Alexpux/MSYS2-packages#707]
The msys `python`'s `ctypes` support seems to be broken with `msys2-runtime` versions newer than 2.5.0.
```
$ /usr/bin/python
>>> import ctypes
>>> ctypes.cdll.kernel32
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/ctypes/__init__.py", line 421, in __getattr__
    dll = self._dlltype(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: No such file or directory
```
This was originally noticed in [GHC bug #12661](https://ghc.haskell.org/trac/ghc/ticket/12661).

**Comment by Mistuke** [comment]
I think `2.5.1` also works (don't remember precisely) but `2.5.2` is definitely broken.

**Comment by RyanGlScott** [comment]
An interesting [note from the Python docs](https://docs.python.org/3/library/ctypes.html#loading-dynamic-link-libraries):

> On Linux, it is required to specify the filename _including_ the extension to load a library, so attribute access can not be used to load libraries. Either the `LoadLibrary()` method of the dll loaders should be used, or you should load the library by creating an instance of CDLL by calling the constructor:
> 
> ```
> >>> cdll.LoadLibrary("libc.so.6")  
> <CDLL 'libc.so.6', handle ... at ...>
> >>> libc = CDLL("libc.so.6")       
> >>> libc                           
> <CDLL 'libc.so.6', handle ... at ...>
> >>>
> ```

This might serve as a workaround, since the following appears to work with the MSYS2 version of Python:

```
$ /usr/bin/python
Python 3.4.3 (default, Mar  4 2016, 10:23:36)
[GCC 4.9.2] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ctypes.cdll.LoadLibrary("kernel32.dll")
<CDLL 'kernel32.dll', handle 7ff941170000 at 6ffffcd0a20>
>>> ctypes.CDLL("kernel32.dll")
<CDLL 'kernel32.dll', handle 7ff941170000 at 6ffffcd0a58>

$ /usr/bin/python --version
Python 3.4.3

$ uname -r
2.6.0(0.304/5/3)
```

**Comment by yukoff** [comment]
Seems I hit similar problem with buck, however I was able to fix it by this (seems to be working with eithr python 2 or 3):
  * this is for python3
```python
$ python3
$ python3
Python 3.4.3 (default, Mar  4 2016, 10:23:36)
[GCC 4.9.2] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ctypes.CDLL('kernel32.dll', use_errno=True)
<CDLL 'kernel32.dll', handle 7ff8a03f0000 at 6ffffd16cc0>
>>> quit()
```

* and this is for python2
```python
$ python2
Python 2.7.11 (default, Mar  4 2016, 10:54:03)
[GCC 4.9.2] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes
>>> ctypes.CDLL('kernel32.dll', use_errno=True)
<CDLL 'kernel32.dll', handle 7ff8a03f0000 at 6ffffe61f90>
>>> quit()
```
