### ISSUE TITLE
mingw64 python2 does not have ssl support

### ISSUE THREAD

**Issue by iongion** [Alexpux/MSYS2-packages#708]
Available pythons:

```
$ where python2
W:\SDKs\msys2\mingw64\bin\python2
W:\SDKs\msys2\mingw64\bin\python2.exe
W:\SDKs\msys2\usr\bin\python2.exe
```

Testing SSL support for mingw64:
```
$ /mingw64/bin/python2
Python 2.7.12 (default, Sep 24 2016, 09:15:29)  [GCC 6.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "W:\SDKs\msys2\usr\lib\python2.7/ssl.py", line 138, in <module>
    from _ssl import enum_certificates, enum_crls
ImportError: cannot import name enum_certificates
>>>
```

I have installed pygtk: `mingw64/mingw-w64-x86_64-python2-pygtk 2.24.0-6 [installed]`
But pygtk-demo does not work:
```
$ pygtk-demo
Traceback (most recent call last):
  File "W:/SDKs/msys2/mingw64/bin/pygtk-demo", line 7, in <module>
    execfile(os.path.join(pygtklibdir, "pygtk-demo.py"))
  File "W:/SDKs/msys2/mingw64\lib\pygtk\2.0\pygtk-demo.py", line 13, in <module>
    import pygtk
ImportError: No module named pygtk
```
Due to lack of SSL support pip and setuptools don't work

Now for the other python, testing SSL support for msys:
```
$ /usr/bin/python2
Python 2.7.11 (default, Mar  4 2016, 10:54:03)
[GCC 4.9.2] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.socket
<class 'socket._socketobject'>
>>>
```

- Is there a solution to this ?
- Is there a way to get pygtk-demo to work ?

**Comment by mati865** [comment]
You are running mingw Python from MSYS2 shell: `File "W:\SDKs\msys2\usr\lib\python2.7/ssl.py", line 138, in <module>`.
You have to call it from MINGW32 or MINGW64 shell. Then both SSL and pygtk-demo are working.

**Comment by iongion** [comment]
Damn! Confusion! You are right - it was the wrong environment
